package com.vogella.groovy.database.h2
import groovy.sql.Sql

import java.util.logging.*

def db = Sql.newInstance('jdbc:h2:mem:GinA','sa','','org.h2.Driver')

db.execute '''
DROP
INDEX athleteIdx IF EXISTS;
DROP
TABLE Athlete
IF EXISTS;
CREATE TABLE Athlete (
athleteId
INTEGER GENERATED BY DEFAULT AS IDENTITY,
firstname
VARCHAR(64),
lastname
VARCHAR(64),
dateOfBirth DATE
);
CREATE INDEX athleteIdx ON Athlete (athleteId);
'''
def athletes = [
	[first: 'Paul',
		last: 'Tergat',
		birth: '1969-06-17'],
	[first: 'Khalid', last: 'Khannouchi', birth: '1971-12-22'],
	[first: 'Ronaldo', last: 'da Costa',
		birth: '1970-06-07']
]
athletes.each { athlete -> db.execute """
INSERT INTO Athlete (firstname, lastname, dateOfBirth)
VALUES (${athlete.first}, ${athlete.last}, ${athlete.birth});
"""
}

println ' Athlete Info '.center(25,'-')
def fmt = new java.text.SimpleDateFormat('dd. MMM yyyy (E)',
		Locale.US)
db.eachRow('SELECT * FROM Athlete'){ athlete ->
	println athlete.firstname + ' ' + athlete.lastname
	println 'born on '+ fmt.format(athlete.dateOfBirth)
	println '-' * 25
}
